### ISSUE TITLE
Checklist of suggested features

### ISSUE THREAD

**Issue by NStefan002** [NStefan002/screenkey.nvim#13]
- [x] Allow blacklisting certain buffers (by @Davidyz in #6)
- [x] Clear Screenkey after some time (by u/evergreengt on Reddit)
- [ ] Add a debug option (by @Makaze)
- [ ] Key grouping (by u/OkDifference646 on Reddit)
- [ ] Make window persistent - cannot be closed by something like `<c-w>o` (by u/yetAnotherOfMe on Reddit)
- [ ] Screenkey should always be on the visible tab (by u/yetAnotherOfMe on Reddit)

If you want to suggest any features, feel free to open up a feature request.
